name: Hukum
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.4.0
  firebase_auth: ^4.4.0
  date_format: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0 # Add the latest version of flutter_svg here
  google_sign_in: ^5.0.7


dev_dependencies:
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  google_sign_in: ^5.0.7


flutter:
  assets:
    - assets/splashscreen1.jpg
#    - assets/welcome_image.jpg
    - assets/welcome_image2.jpg
    - assets/signinbackground.jpg
    - assets/welcome_image3.jpg
    - assets/icons/



