name: Hukum
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.4.0
  firebase_auth: ^4.4.0
  date_format: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0 # Add the latest version of flutter_svg here
  google_sign_in: ^5.0.7


dev_dependencies:
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  google_sign_in: ^5.0.7


flutter:
  assets:
    - assets/splashscreen1.jpg
#    - assets/welcome_image.jpg
    - assets/welcome_image2.jpg
    - assets/signinbackground.jpg
    - assets/welcome_image3.jpg
    - assets/icons/
    - assets/welcome_image1.jpg
    - assets/signinbackground2.jpg
    - assets/email_icon.svg
    - assets/facebook_icon.svg
    - assets/google_icon.svg
    - assets/phone_icon.svg










#
#
#    - packages/auth_buttons/images/default/apple.svg
#    - packages/auth_buttons/images/default/email.svg
#    - packages/auth_buttons/images/default/facebook.svg
#    - packages/auth_buttons/images/default/github_black.svg
#    - packages/auth_buttons/images/default/google.svg
#    - packages/auth_buttons/images/default/huawei.svg
#    - packages/auth_buttons/images/default/microsoft.svg
#    - packages/auth_buttons/images/default/twitter.svg
#
#    - packages/auth_buttons/images/outlined/apple.svg
#    - packages/auth_buttons/images/outlined/email.svg
#    - packages/auth_buttons/images/outlined/facebook.svg
#    - packages/auth_buttons/images/outlined/github.svg
#    - packages/auth_buttons/images/outlined/google.svg
#    - packages/auth_buttons/images/outlined/huawei.svg
#    - packages/auth_buttons/images/outlined/microsoft.svg
#    - packages/auth_buttons/images/outlined/twitter.svg
#
#    - packages/auth_buttons/images/secondary/apple.svg
#    - packages/auth_buttons/images/secondary/email.svg
#    - packages/auth_buttons/images/secondary/facebook.svg
#    - packages/auth_buttons/images/secondary/github.svg
#    - packages/auth_buttons/images/secondary/google.svg
#    - packages/auth_buttons/images/secondary/huawei.svg
#    - packages/auth_buttons/images/secondary/microsoft.svg
#    - packages/auth_buttons/images/secondary/twitter.svg
#
#
